/* Generated By:JavaCC: Do not edit this line. TestParserConstants.java */
package net.sf.crsx.samples.test;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TestParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_meta1_T_M_E = 4;
  /** RegularExpression Id. */
  int T_meta2_T_M_E = 8;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_META_T_M_E = 1;
  /** Lexical state. */
  int IN_NESTED_META_T_M_E = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"0\"",
    "\"do\"",
    "\"od\"",
    "<T_meta1_T_M_E>",
    "<token of kind 5>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 9>",
    "\" \"",
  };

}
