/* Generated By:JavaCC: Do not edit this line. TextConstants.java */
package net.sf.crsx.text;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TextConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_CHARS = 9;
  /** RegularExpression Id. */
  int T_BREAK = 10;
  /** RegularExpression Id. */
  int T_EMBEDDED = 11;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\u00b6\"",
    "\"\\u27e6\"",
    "\"\\u27e7\"",
    "\"\\u201c\"",
    "\"\\u201d\"",
    "\"\\u2020\"",
    "\"\\u2021\"",
    "\"\\u2227\"",
    "<T_CHARS>",
    "<T_BREAK>",
    "<T_EMBEDDED>",
  };

}
