# Makefile for generating the XQuery 1.0 grammar

# HACS configuration.
HACS = $(abspath ../../crsx/samples/gentle/hacs)
include $(HACS)/Makefile-hx

# Hacs target.
all:: hacs.run
hacs.run: hacs.hx 


# Example
# hacs.run --sort=Module samples/hacs-1.hx
