/* Generated By:JavaCC: Do not edit this line. DerivParserConstants.java */
package net.sf.crsx.samples.guide;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DerivParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_meta1_T_M_B = 8;
  /** RegularExpression Id. */
  int T_meta2_T_M_B = 12;
  /** RegularExpression Id. */
  int T_meta1_T_M_EXP = 22;
  /** RegularExpression Id. */
  int T_meta2_T_M_EXP = 26;
  /** RegularExpression Id. */
  int T_meta1_T_M_FUN = 33;
  /** RegularExpression Id. */
  int T_meta2_T_M_FUN = 37;
  /** RegularExpression Id. */
  int T_meta1_T_M_INT = 39;
  /** RegularExpression Id. */
  int T_meta2_T_M_INT = 43;
  /** RegularExpression Id. */
  int T_meta1_T_M_VAR = 45;
  /** RegularExpression Id. */
  int T_meta2_T_M_VAR = 49;
  /** RegularExpression Id. */
  int T_NESTED_T_M_SPACE_S = 54;
  /** RegularExpression Id. */
  int T_T_M_INT = 56;
  /** RegularExpression Id. */
  int T_T_M_VAR = 57;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_META_T_M_B = 1;
  /** Lexical state. */
  int IN_NESTED_META_T_M_B = 2;
  /** Lexical state. */
  int IN_META_T_M_EXP = 3;
  /** Lexical state. */
  int IN_NESTED_META_T_M_EXP = 4;
  /** Lexical state. */
  int IN_META_T_M_FUN = 5;
  /** Lexical state. */
  int IN_NESTED_META_T_M_FUN = 6;
  /** Lexical state. */
  int IN_META_T_M_INT = 7;
  /** Lexical state. */
  int IN_NESTED_META_T_M_INT = 8;
  /** Lexical state. */
  int IN_META_T_M_VAR = 9;
  /** Lexical state. */
  int IN_NESTED_META_T_M_VAR = 10;
  /** Lexical state. */
  int IN_T_M_SPACE_S = 11;
  /** Lexical state. */
  int IN_NESTED_T_M_SPACE_S = 12;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\u2228\"",
    "\"\\u2227\"",
    "\"\\u00ac\"",
    "\"(\"",
    "\")\"",
    "\"f\"",
    "\"t\"",
    "<T_meta1_T_M_B>",
    "<token of kind 9>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 13>",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"D\"",
    "\"[\"",
    "\"\\u21a6\"",
    "\"]\"",
    "<T_meta1_T_M_EXP>",
    "<token of kind 23>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 27>",
    "\"\\\'\"",
    "\"cos\"",
    "\"exp\"",
    "\"ln\"",
    "\"sin\"",
    "<T_meta1_T_M_FUN>",
    "<token of kind 34>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 38>",
    "<T_meta1_T_M_INT>",
    "<token of kind 40>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 44>",
    "<T_meta1_T_M_VAR>",
    "<token of kind 46>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 50>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 55>",
    "<T_T_M_INT>",
    "<T_T_M_VAR>",
    "<token of kind 58>",
  };

}
