/* Generated By:JavaCC: Do not edit this line. FirstParserConstants.java */
package net.sf.crsx.samples.gentle;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FirstParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int T_meta1_T_M_INT = 1;
  /** RegularExpression Id. */
  int T_meta2_T_M_INT = 5;
  /** RegularExpression Id. */
  int T_meta1_T_M_FLOAT = 7;
  /** RegularExpression Id. */
  int T_meta2_T_M_FLOAT = 11;
  /** RegularExpression Id. */
  int T_meta1_T_M_ID = 13;
  /** RegularExpression Id. */
  int T_meta2_T_M_ID = 17;
  /** RegularExpression Id. */
  int T_meta1_T_M_STAT = 25;
  /** RegularExpression Id. */
  int T_meta2_T_M_STAT = 29;
  /** RegularExpression Id. */
  int T_meta1_T_M_EXP = 35;
  /** RegularExpression Id. */
  int T_meta2_T_M_EXP = 39;
  /** RegularExpression Id. */
  int T_meta1_T_M_NAME = 41;
  /** RegularExpression Id. */
  int T_meta2_T_M_NAME = 45;
  /** RegularExpression Id. */
  int T_meta1_T_M_T = 47;
  /** RegularExpression Id. */
  int T_meta2_T_M_T = 51;
  /** RegularExpression Id. */
  int T_meta1_T_M_I_XPROGR = 55;
  /** RegularExpression Id. */
  int T_meta2_T_M_I_XPROGR = 59;
  /** RegularExpression Id. */
  int T_meta1_T_M_I_XINSTR = 62;
  /** RegularExpression Id. */
  int T_meta2_T_M_I_XINSTR = 66;
  /** RegularExpression Id. */
  int T_meta1_T_M_I_XARG = 68;
  /** RegularExpression Id. */
  int T_meta2_T_M_I_XARG = 72;
  /** RegularExpression Id. */
  int T_meta1_T_M_TMP = 74;
  /** RegularExpression Id. */
  int T_meta2_T_M_TMP = 78;
  /** RegularExpression Id. */
  int T_meta1_T_M_A_XPROGR = 82;
  /** RegularExpression Id. */
  int T_meta2_T_M_A_XPROGR = 86;
  /** RegularExpression Id. */
  int T_meta1_T_M_A_XINSTR = 93;
  /** RegularExpression Id. */
  int T_meta2_T_M_A_XINSTR = 97;
  /** RegularExpression Id. */
  int T_meta1_T_M_A_XARG = 102;
  /** RegularExpression Id. */
  int T_meta2_T_M_A_XARG = 106;
  /** RegularExpression Id. */
  int T_meta1_T_M_STAT_XMAYBESOME = 108;
  /** RegularExpression Id. */
  int T_meta2_T_M_STAT_XMAYBESOME = 112;
  /** RegularExpression Id. */
  int T_T_M_INT = 115;
  /** RegularExpression Id. */
  int T_T_M_FLOAT = 116;
  /** RegularExpression Id. */
  int T_T_M_ID = 117;
  /** RegularExpression Id. */
  int T_T_M_DIGIT = 118;
  /** RegularExpression Id. */
  int T_T_M_LOWER = 119;
  /** RegularExpression Id. */
  int T_T_M_T = 120;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_META_T_M_INT = 1;
  /** Lexical state. */
  int IN_NESTED_META_T_M_INT = 2;
  /** Lexical state. */
  int IN_META_T_M_FLOAT = 3;
  /** Lexical state. */
  int IN_NESTED_META_T_M_FLOAT = 4;
  /** Lexical state. */
  int IN_META_T_M_ID = 5;
  /** Lexical state. */
  int IN_NESTED_META_T_M_ID = 6;
  /** Lexical state. */
  int IN_META_T_M_STAT = 7;
  /** Lexical state. */
  int IN_NESTED_META_T_M_STAT = 8;
  /** Lexical state. */
  int IN_META_T_M_EXP = 9;
  /** Lexical state. */
  int IN_NESTED_META_T_M_EXP = 10;
  /** Lexical state. */
  int IN_META_T_M_NAME = 11;
  /** Lexical state. */
  int IN_NESTED_META_T_M_NAME = 12;
  /** Lexical state. */
  int IN_META_T_M_T = 13;
  /** Lexical state. */
  int IN_NESTED_META_T_M_T = 14;
  /** Lexical state. */
  int IN_META_T_M_I_XPROGR = 15;
  /** Lexical state. */
  int IN_NESTED_META_T_M_I_XPROGR = 16;
  /** Lexical state. */
  int IN_META_T_M_I_XINSTR = 17;
  /** Lexical state. */
  int IN_NESTED_META_T_M_I_XINSTR = 18;
  /** Lexical state. */
  int IN_META_T_M_I_XARG = 19;
  /** Lexical state. */
  int IN_NESTED_META_T_M_I_XARG = 20;
  /** Lexical state. */
  int IN_META_T_M_TMP = 21;
  /** Lexical state. */
  int IN_NESTED_META_T_M_TMP = 22;
  /** Lexical state. */
  int IN_META_T_M_A_XPROGR = 23;
  /** Lexical state. */
  int IN_NESTED_META_T_M_A_XPROGR = 24;
  /** Lexical state. */
  int IN_META_T_M_A_XINSTR = 25;
  /** Lexical state. */
  int IN_NESTED_META_T_M_A_XINSTR = 26;
  /** Lexical state. */
  int IN_META_T_M_A_XARG = 27;
  /** Lexical state. */
  int IN_NESTED_META_T_M_A_XARG = 28;
  /** Lexical state. */
  int IN_META_T_M_STAT_XMAYBESOME = 29;
  /** Lexical state. */
  int IN_NESTED_META_T_M_STAT_XMAYBESOME = 30;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<T_meta1_T_M_INT>",
    "<token of kind 2>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 6>",
    "<T_meta1_T_M_FLOAT>",
    "<token of kind 8>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 12>",
    "<T_meta1_T_M_ID>",
    "<token of kind 14>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 18>",
    "\"TA\"",
    "\"TA2\"",
    "\"{\"",
    "\"}\"",
    "\":=\"",
    "\";\"",
    "<T_meta1_T_M_STAT>",
    "<token of kind 26>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 30>",
    "\"+\"",
    "\"*\"",
    "\"(\"",
    "\")\"",
    "<T_meta1_T_M_EXP>",
    "<token of kind 36>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 40>",
    "<T_meta1_T_M_NAME>",
    "<token of kind 42>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 46>",
    "<T_meta1_T_M_T>",
    "<token of kind 48>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 52>",
    "\"ICG\"",
    "\"ICGExp\"",
    "<T_meta1_T_M_I_XPROGR>",
    "<token of kind 56>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 60>",
    "\"=\"",
    "<T_meta1_T_M_I_XINSTR>",
    "<token of kind 63>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 67>",
    "<T_meta1_T_M_I_XARG>",
    "<token of kind 69>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 73>",
    "<T_meta1_T_M_TMP>",
    "<token of kind 75>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 79>",
    "\"CG\"",
    "\"Compile\"",
    "<T_meta1_T_M_A_XPROGR>",
    "<token of kind 83>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 87>",
    "\"ADDF\"",
    "\",\"",
    "\"LDF\"",
    "\"MULF\"",
    "\"STF\"",
    "<T_meta1_T_M_A_XINSTR>",
    "<token of kind 94>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 98>",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "<T_meta1_T_M_A_XARG>",
    "<token of kind 103>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 107>",
    "<T_meta1_T_M_STAT_XMAYBESOME>",
    "<token of kind 109>",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "\"\\u27e9\"",
    "<token of kind 113>",
    "<token of kind 114>",
    "<T_T_M_INT>",
    "<T_T_M_FLOAT>",
    "<T_T_M_ID>",
    "<T_T_M_DIGIT>",
    "<T_T_M_LOWER>",
    "<T_T_M_T>",
  };

}
