/* Generated By:JavaCC: Do not edit this line. PGParserConstants.java */
package net.sf.crsx.pg;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PGParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LANGLE = 52;
  /** RegularExpression Id. */
  int RANGLE = 53;
  /** RegularExpression Id. */
  int DASH = 54;
  /** RegularExpression Id. */
  int NOT = 55;
  /** RegularExpression Id. */
  int COMMENT = 56;
  /** RegularExpression Id. */
  int STRING = 57;
  /** RegularExpression Id. */
  int EMBEDDED = 58;
  /** RegularExpression Id. */
  int VAR = 59;
  /** RegularExpression Id. */
  int CONST = 60;
  /** RegularExpression Id. */
  int NUMBER = 61;
  /** RegularExpression Id. */
  int METAVAR = 62;
  /** RegularExpression Id. */
  int DIGIT = 63;
  /** RegularExpression Id. */
  int LOWER = 64;
  /** RegularExpression Id. */
  int UPPER = 65;
  /** RegularExpression Id. */
  int LETTER = 66;
  /** RegularExpression Id. */
  int TAIL = 67;
  /** RegularExpression Id. */
  int CHAR = 68;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_LINE_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"class\"",
    "\"grammar\"",
    "\":\"",
    "\",\"",
    "\"prefix\"",
    "\"options\"",
    "\"=\"",
    "\"imports\"",
    "\"declarations\"",
    "\"$\"",
    "\"(\"",
    "\"*\"",
    "\")\"",
    "\"::=\"",
    "\"|\"",
    "\".\"",
    "\"token\"",
    "\"fragment\"",
    "\"skip\"",
    "\"cast\"",
    "\"[\"",
    "\"]\"",
    "\"meta\"",
    "\"nometa\"",
    "\"inject\"",
    "\"noinject\"",
    "\"+\"",
    "\"?\"",
    "\"{\"",
    "\"}\"",
    "\"EOF\"",
    "\"include\"",
    "\"JavaCC\"",
    "\"^\"",
    "\"!\"",
    "\"@\"",
    "\"_\"",
    "\"~\"",
    "\"#\"",
    "\"%\"",
    "\"&\"",
    "\";\"",
    "\"/\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"//\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 51>",
    "<LANGLE>",
    "<RANGLE>",
    "<DASH>",
    "<NOT>",
    "<COMMENT>",
    "<STRING>",
    "<EMBEDDED>",
    "<VAR>",
    "<CONST>",
    "<NUMBER>",
    "<METAVAR>",
    "<DIGIT>",
    "<LOWER>",
    "<UPPER>",
    "<LETTER>",
    "<TAIL>",
    "<CHAR>",
  };

}
