/* Generated By:JavaCC: Do not edit this line. RawConstants.java */
package net.sf.crsx.hoacs.bootstrap;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface RawConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int MT_Module = 1;
  /** RegularExpression Id. */
  int IT_Module = 2;
  /** RegularExpression Id. */
  int MT_EmbeddedModule = 6;
  /** RegularExpression Id. */
  int IT_EmbeddedModule = 7;
  /** RegularExpression Id. */
  int MT_Declarations = 8;
  /** RegularExpression Id. */
  int IT_Declarations = 9;
  /** RegularExpression Id. */
  int MT_Declaration = 10;
  /** RegularExpression Id. */
  int IT_Declaration = 11;
  /** RegularExpression Id. */
  int MT_RegExp = 12;
  /** RegularExpression Id. */
  int IT_RegExp = 13;
  /** RegularExpression Id. */
  int MT_RegExpChoice = 14;
  /** RegularExpression Id. */
  int IT_RegExpChoice = 15;
  /** RegularExpression Id. */
  int MT_RegExpUnits = 16;
  /** RegularExpression Id. */
  int IT_RegExpUnits = 17;
  /** RegularExpression Id. */
  int MT_RegExpUnit = 18;
  /** RegularExpression Id. */
  int IT_RegExpUnit = 19;
  /** RegularExpression Id. */
  int MT_Repeat = 20;
  /** RegularExpression Id. */
  int IT_Repeat = 21;
  /** RegularExpression Id. */
  int MT_RegExpLeaf = 22;
  /** RegularExpression Id. */
  int IT_RegExpLeaf = 23;
  /** RegularExpression Id. */
  int MT_RegExpSimple = 24;
  /** RegularExpression Id. */
  int IT_RegExpSimple = 25;
  /** RegularExpression Id. */
  int MT_AttributeForm = 26;
  /** RegularExpression Id. */
  int IT_AttributeForm = 27;
  /** RegularExpression Id. */
  int MT_AttributeOptions = 28;
  /** RegularExpression Id. */
  int IT_AttributeOptions = 29;
  /** RegularExpression Id. */
  int MT_AttributeOption = 30;
  /** RegularExpression Id. */
  int IT_AttributeOption = 31;
  /** RegularExpression Id. */
  int MT_SortNames = 32;
  /** RegularExpression Id. */
  int IT_SortNames = 33;
  /** RegularExpression Id. */
  int MT_SortAbstraction = 34;
  /** RegularExpression Id. */
  int IT_SortAbstraction = 35;
  /** RegularExpression Id. */
  int MT_SortAlternatives = 36;
  /** RegularExpression Id. */
  int IT_SortAlternatives = 37;
  /** RegularExpression Id. */
  int MT_SortAlternative = 38;
  /** RegularExpression Id. */
  int IT_SortAlternative = 39;
  /** RegularExpression Id. */
  int MT_Form = 40;
  /** RegularExpression Id. */
  int IT_Form = 41;
  /** RegularExpression Id. */
  int MT_ScopeSorts = 42;
  /** RegularExpression Id. */
  int IT_ScopeSorts = 43;
  /** RegularExpression Id. */
  int MT_ScopeSort = 44;
  /** RegularExpression Id. */
  int IT_ScopeSort = 45;
  /** RegularExpression Id. */
  int MT_SubstituteSorts = 46;
  /** RegularExpression Id. */
  int IT_SubstituteSorts = 47;
  /** RegularExpression Id. */
  int MT_SubstituteSort = 48;
  /** RegularExpression Id. */
  int IT_SubstituteSort = 49;
  /** RegularExpression Id. */
  int MT_Sort = 50;
  /** RegularExpression Id. */
  int IT_Sort = 51;
  /** RegularExpression Id. */
  int MT_SimpleSorts = 52;
  /** RegularExpression Id. */
  int IT_SimpleSorts = 53;
  /** RegularExpression Id. */
  int MT_SimpleSort = 54;
  /** RegularExpression Id. */
  int IT_SimpleSort = 55;
  /** RegularExpression Id. */
  int MT_MetaVariables = 56;
  /** RegularExpression Id. */
  int IT_MetaVariables = 57;
  /** RegularExpression Id. */
  int MT_SortParam = 58;
  /** RegularExpression Id. */
  int IT_SortParam = 59;
  /** RegularExpression Id. */
  int MT_ParsedForm = 60;
  /** RegularExpression Id. */
  int IT_ParsedForm = 61;
  /** RegularExpression Id. */
  int MT_FormPrec = 62;
  /** RegularExpression Id. */
  int IT_FormPrec = 63;
  /** RegularExpression Id. */
  int MT_Tagging = 64;
  /** RegularExpression Id. */
  int IT_Tagging = 65;
  /** RegularExpression Id. */
  int MT_InheritedRefs = 66;
  /** RegularExpression Id. */
  int IT_InheritedRefs = 67;
  /** RegularExpression Id. */
  int MT_InheritedRef = 68;
  /** RegularExpression Id. */
  int IT_InheritedRef = 69;
  /** RegularExpression Id. */
  int MT_Rule = 70;
  /** RegularExpression Id. */
  int IT_Rule = 71;
  /** RegularExpression Id. */
  int MT_Priority = 72;
  /** RegularExpression Id. */
  int IT_Priority = 73;
  /** RegularExpression Id. */
  int MT_Term = 74;
  /** RegularExpression Id. */
  int IT_Term = 75;
  /** RegularExpression Id. */
  int MT_NotVariableTerm = 76;
  /** RegularExpression Id. */
  int IT_NotVariableTerm = 77;
  /** RegularExpression Id. */
  int MT_Construction = 78;
  /** RegularExpression Id. */
  int IT_Construction = 79;
  /** RegularExpression Id. */
  int MT_Scopes = 80;
  /** RegularExpression Id. */
  int IT_Scopes = 81;
  /** RegularExpression Id. */
  int MT_Scope = 82;
  /** RegularExpression Id. */
  int IT_Scope = 83;
  /** RegularExpression Id. */
  int MT_Variables = 84;
  /** RegularExpression Id. */
  int IT_Variables = 85;
  /** RegularExpression Id. */
  int MT_VariableList = 86;
  /** RegularExpression Id. */
  int IT_VariableList = 87;
  /** RegularExpression Id. */
  int MT_Terms = 88;
  /** RegularExpression Id. */
  int IT_Terms = 89;
  /** RegularExpression Id. */
  int MT_Parsed = 90;
  /** RegularExpression Id. */
  int IT_Parsed = 91;
  /** RegularExpression Id. */
  int MT_Attributes = 92;
  /** RegularExpression Id. */
  int IT_Attributes = 93;
  /** RegularExpression Id. */
  int MT_Attribute = 94;
  /** RegularExpression Id. */
  int IT_Attribute = 95;
  /** RegularExpression Id. */
  int MT_AttributeKind = 96;
  /** RegularExpression Id. */
  int IT_AttributeKind = 97;
  /** RegularExpression Id. */
  int MT_AttributeValue = 98;
  /** RegularExpression Id. */
  int IT_AttributeValue = 99;
  /** RegularExpression Id. */
  int MT_ConcreteSpace = 100;
  /** RegularExpression Id. */
  int IT_ConcreteSpace = 101;
  /** RegularExpression Id. */
  int MT_ConcreteWord = 102;
  /** RegularExpression Id. */
  int IT_ConcreteWord = 103;
  /** RegularExpression Id. */
  int MT_ModuleName = 108;
  /** RegularExpression Id. */
  int IT_ModuleName = 109;
  /** RegularExpression Id. */
  int MT_SortName = 110;
  /** RegularExpression Id. */
  int IT_SortName = 111;
  /** RegularExpression Id. */
  int MT_FragmentName = 112;
  /** RegularExpression Id. */
  int IT_FragmentName = 113;
  /** RegularExpression Id. */
  int MT_FragmentRef = 114;
  /** RegularExpression Id. */
  int IT_FragmentRef = 115;
  /** RegularExpression Id. */
  int MT_AttributeName = 116;
  /** RegularExpression Id. */
  int IT_AttributeName = 117;
  /** RegularExpression Id. */
  int MT_Constructor = 118;
  /** RegularExpression Id. */
  int IT_Constructor = 119;
  /** RegularExpression Id. */
  int MT_Variable = 120;
  /** RegularExpression Id. */
  int IT_Variable = 121;
  /** RegularExpression Id. */
  int MT_MetaVariable = 122;
  /** RegularExpression Id. */
  int IT_MetaVariable = 123;
  /** RegularExpression Id. */
  int MT_Separator = 124;
  /** RegularExpression Id. */
  int IT_Separator = 125;
  /** RegularExpression Id. */
  int MT_Literal = 126;
  /** RegularExpression Id. */
  int IT_Literal = 127;
  /** RegularExpression Id. */
  int MT_Number = 128;
  /** RegularExpression Id. */
  int IT_Number = 129;
  /** RegularExpression Id. */
  int MT_Natural = 130;
  /** RegularExpression Id. */
  int IT_Natural = 131;
  /** RegularExpression Id. */
  int MT_String = 132;
  /** RegularExpression Id. */
  int IT_String = 133;
  /** RegularExpression Id. */
  int MT_Word = 134;
  /** RegularExpression Id. */
  int IT_Word = 135;
  /** RegularExpression Id. */
  int MT_RegExpClass = 136;
  /** RegularExpression Id. */
  int IT_RegExpClass = 137;
  /** RegularExpression Id. */
  int MT_CC = 138;
  /** RegularExpression Id. */
  int IT_CC = 139;
  /** RegularExpression Id. */
  int MT_CC_RangesTop = 140;
  /** RegularExpression Id. */
  int IT_CC_RangesTop = 141;
  /** RegularExpression Id. */
  int MT_CC_Ranges = 142;
  /** RegularExpression Id. */
  int IT_CC_Ranges = 143;
  /** RegularExpression Id. */
  int MT_CC_RangeTail = 144;
  /** RegularExpression Id. */
  int IT_CC_RangeTail = 145;
  /** RegularExpression Id. */
  int MT_CC_FirstRangeStartChar = 146;
  /** RegularExpression Id. */
  int IT_CC_FirstRangeStartChar = 147;
  /** RegularExpression Id. */
  int MT_CC_NonDashRangeStartChar = 148;
  /** RegularExpression Id. */
  int IT_CC_NonDashRangeStartChar = 149;
  /** RegularExpression Id. */
  int MT_CC_RangeChar = 150;
  /** RegularExpression Id. */
  int IT_CC_RangeChar = 151;
  /** RegularExpression Id. */
  int T_Embedded = 152;
  /** RegularExpression Id. */
  int T_CONCRETESTART = 153;
  /** RegularExpression Id. */
  int T_CONCRETEEND = 154;
  /** RegularExpression Id. */
  int T_CONCRETEPUSH = 155;
  /** RegularExpression Id. */
  int T_CONCRETEPOP = 156;
  /** RegularExpression Id. */
  int T_CONCRETESPACE = 157;
  /** RegularExpression Id. */
  int T_CONCRETEWORD = 158;
  /** RegularExpression Id. */
  int T_SEMI = 160;
  /** RegularExpression Id. */
  int T_BAR = 161;
  /** RegularExpression Id. */
  int T_LPAREN = 162;
  /** RegularExpression Id. */
  int T_RPAREN = 163;
  /** RegularExpression Id. */
  int T_STAR = 164;
  /** RegularExpression Id. */
  int T_PLUS = 165;
  /** RegularExpression Id. */
  int T_QUEST = 166;
  /** RegularExpression Id. */
  int T_SUB = 167;
  /** RegularExpression Id. */
  int T_DOT = 168;
  /** RegularExpression Id. */
  int T_COLON = 169;
  /** RegularExpression Id. */
  int T_LBRACE = 170;
  /** RegularExpression Id. */
  int T_RBRACE = 171;
  /** RegularExpression Id. */
  int T_HASH = 172;
  /** RegularExpression Id. */
  int T_LBRACKET = 173;
  /** RegularExpression Id. */
  int T_RBRACKET = 174;
  /** RegularExpression Id. */
  int T_COMMA = 175;
  /** RegularExpression Id. */
  int T_FORALL = 176;
  /** RegularExpression Id. */
  int T_ARROW = 177;
  /** RegularExpression Id. */
  int T_UP = 178;
  /** RegularExpression Id. */
  int T_DOWN = 179;
  /** RegularExpression Id. */
  int T_NOT = 180;
  /** RegularExpression Id. */
  int T_AT = 181;
  /** RegularExpression Id. */
  int T_DASH = 182;
  /** RegularExpression Id. */
  int T_DIGIT = 183;
  /** RegularExpression Id. */
  int T_LOWER = 184;
  /** RegularExpression Id. */
  int T_UPPER = 185;
  /** RegularExpression Id. */
  int T_MODULE = 186;
  /** RegularExpression Id. */
  int T_SORT = 187;
  /** RegularExpression Id. */
  int T_DATA = 188;
  /** RegularExpression Id. */
  int T_SCHEME = 189;
  /** RegularExpression Id. */
  int T_AUTOMATIC = 190;
  /** RegularExpression Id. */
  int T_SYMBOL = 191;
  /** RegularExpression Id. */
  int T_STATIC = 192;
  /** RegularExpression Id. */
  int T_ATTRIBUTE = 193;
  /** RegularExpression Id. */
  int T_COMPOSE = 194;
  /** RegularExpression Id. */
  int T_SUGAR = 195;
  /** RegularExpression Id. */
  int T_RULE = 196;
  /** RegularExpression Id. */
  int T_PRIORITY = 197;
  /** RegularExpression Id. */
  int T_DEFAULT = 198;
  /** RegularExpression Id. */
  int T_IMPORT = 199;
  /** RegularExpression Id. */
  int T_TAG = 200;
  /** RegularExpression Id. */
  int T_SPACE = 201;
  /** RegularExpression Id. */
  int T_TOKEN = 202;
  /** RegularExpression Id. */
  int T_FRAGMENT = 203;
  /** RegularExpression Id. */
  int T_NESTED = 204;
  /** RegularExpression Id. */
  int T_META = 205;
  /** RegularExpression Id. */
  int T_VAR = 206;
  /** RegularExpression Id. */
  int T_CON = 207;
  /** RegularExpression Id. */
  int T_SUFFIX = 208;
  /** RegularExpression Id. */
  int T_NAME = 209;
  /** RegularExpression Id. */
  int T_FRAGMENT_REF = 210;
  /** RegularExpression Id. */
  int T_NATURAL = 211;
  /** RegularExpression Id. */
  int T_INTEGER = 212;
  /** RegularExpression Id. */
  int T_UNNATURAL = 213;
  /** RegularExpression Id. */
  int T_STRING = 214;
  /** RegularExpression Id. */
  int T_STRING1CHAR = 215;
  /** RegularExpression Id. */
  int T_STRING2CHAR = 216;
  /** RegularExpression Id. */
  int T_ESCAPEDCHAR = 217;
  /** RegularExpression Id. */
  int T_HEX = 218;
  /** RegularExpression Id. */
  int T_OTHERCHAR = 219;
  /** RegularExpression Id. */
  int T_WORD = 220;
  /** RegularExpression Id. */
  int T_CHAR_CLASS = 221;
  /** RegularExpression Id. */
  int T_CC_NOT = 222;
  /** RegularExpression Id. */
  int T_CC_RBRACKET = 223;
  /** RegularExpression Id. */
  int T_CC_DASH = 224;
  /** RegularExpression Id. */
  int T_CC_OTHER = 225;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int RE = 1;
  /** Lexical state. */
  int NESTED_COMMENT = 2;
  /** Lexical state. */
  int CC = 3;
  /** Lexical state. */
  int CONCRETE = 4;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<MT_Module>",
    "\"%Module\"",
    "\"\\u2983\"",
    "\"\\u2225\"",
    "\"\\u2984\"",
    "<MT_EmbeddedModule>",
    "\"%EmbeddedModule\"",
    "<MT_Declarations>",
    "\"%Declarations\"",
    "<MT_Declaration>",
    "\"%Declaration\"",
    "<MT_RegExp>",
    "\"%RegExp\"",
    "<MT_RegExpChoice>",
    "\"%RegExpChoice\"",
    "<MT_RegExpUnits>",
    "\"%RegExpUnits\"",
    "<MT_RegExpUnit>",
    "\"%RegExpUnit\"",
    "<MT_Repeat>",
    "\"%Repeat\"",
    "<MT_RegExpLeaf>",
    "\"%RegExpLeaf\"",
    "<MT_RegExpSimple>",
    "\"%RegExpSimple\"",
    "<MT_AttributeForm>",
    "\"%AttributeForm\"",
    "<MT_AttributeOptions>",
    "\"%AttributeOptions\"",
    "<MT_AttributeOption>",
    "\"%AttributeOption\"",
    "<MT_SortNames>",
    "\"%SortNames\"",
    "<MT_SortAbstraction>",
    "\"%SortAbstraction\"",
    "<MT_SortAlternatives>",
    "\"%SortAlternatives\"",
    "<MT_SortAlternative>",
    "\"%SortAlternative\"",
    "<MT_Form>",
    "\"%Form\"",
    "<MT_ScopeSorts>",
    "\"%ScopeSorts\"",
    "<MT_ScopeSort>",
    "\"%ScopeSort\"",
    "<MT_SubstituteSorts>",
    "\"%SubstituteSorts\"",
    "<MT_SubstituteSort>",
    "\"%SubstituteSort\"",
    "<MT_Sort>",
    "\"%Sort\"",
    "<MT_SimpleSorts>",
    "\"%SimpleSorts\"",
    "<MT_SimpleSort>",
    "\"%SimpleSort\"",
    "<MT_MetaVariables>",
    "\"%MetaVariables\"",
    "<MT_SortParam>",
    "\"%SortParam\"",
    "<MT_ParsedForm>",
    "\"%ParsedForm\"",
    "<MT_FormPrec>",
    "\"%FormPrec\"",
    "<MT_Tagging>",
    "\"%Tagging\"",
    "<MT_InheritedRefs>",
    "\"%InheritedRefs\"",
    "<MT_InheritedRef>",
    "\"%InheritedRef\"",
    "<MT_Rule>",
    "\"%Rule\"",
    "<MT_Priority>",
    "\"%Priority\"",
    "<MT_Term>",
    "\"%Term\"",
    "<MT_NotVariableTerm>",
    "\"%NotVariableTerm\"",
    "<MT_Construction>",
    "\"%Construction\"",
    "<MT_Scopes>",
    "\"%Scopes\"",
    "<MT_Scope>",
    "\"%Scope\"",
    "<MT_Variables>",
    "\"%Variables\"",
    "<MT_VariableList>",
    "\"%VariableList\"",
    "<MT_Terms>",
    "\"%Terms\"",
    "<MT_Parsed>",
    "\"%Parsed\"",
    "<MT_Attributes>",
    "\"%Attributes\"",
    "<MT_Attribute>",
    "\"%Attribute\"",
    "<MT_AttributeKind>",
    "\"%AttributeKind\"",
    "<MT_AttributeValue>",
    "\"%AttributeValue\"",
    "<MT_ConcreteSpace>",
    "\"%ConcreteSpace\"",
    "<MT_ConcreteWord>",
    "\"%ConcreteWord\"",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 107>",
    "<MT_ModuleName>",
    "\"%ModuleName\"",
    "<MT_SortName>",
    "\"%SortName\"",
    "<MT_FragmentName>",
    "\"%FragmentName\"",
    "<MT_FragmentRef>",
    "\"%FragmentRef\"",
    "<MT_AttributeName>",
    "\"%AttributeName\"",
    "<MT_Constructor>",
    "\"%Constructor\"",
    "<MT_Variable>",
    "\"%Variable\"",
    "<MT_MetaVariable>",
    "\"%MetaVariable\"",
    "<MT_Separator>",
    "\"%Separator\"",
    "<MT_Literal>",
    "\"%Literal\"",
    "<MT_Number>",
    "\"%Number\"",
    "<MT_Natural>",
    "\"%Natural\"",
    "<MT_String>",
    "\"%String\"",
    "<MT_Word>",
    "\"%Word\"",
    "<MT_RegExpClass>",
    "\"%RegExpClass\"",
    "<MT_CC>",
    "\"%CC\"",
    "<MT_CC_RangesTop>",
    "\"%CC_RangesTop\"",
    "<MT_CC_Ranges>",
    "\"%CC_Ranges\"",
    "<MT_CC_RangeTail>",
    "\"%CC_RangeTail\"",
    "<MT_CC_FirstRangeStartChar>",
    "\"%CC_FirstRangeStartChar\"",
    "<MT_CC_NonDashRangeStartChar>",
    "\"%CC_NonDashRangeStartChar\"",
    "<MT_CC_RangeChar>",
    "\"%CC_RangeChar\"",
    "<T_Embedded>",
    "\"\\u27e6\"",
    "\"\\u27e7\"",
    "\"\\u27e8\"",
    "\"\\u27e9\"",
    "<T_CONCRETESPACE>",
    "<T_CONCRETEWORD>",
    "<token of kind 159>",
    "\";\"",
    "\"|\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"+\"",
    "\"?\"",
    "\"_\"",
    "\".\"",
    "\":\"",
    "\"{\"",
    "\"}\"",
    "\"#\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\"\\u2200\"",
    "\"\\u2192\"",
    "\"\\u2191\"",
    "\"\\u2193\"",
    "\"\\u00ac\"",
    "\"@\"",
    "\"-\"",
    "<T_DIGIT>",
    "<T_LOWER>",
    "<T_UPPER>",
    "\"module\"",
    "\"sort\"",
    "\"data\"",
    "\"scheme\"",
    "\"automatic\"",
    "\"symbol\"",
    "\"static\"",
    "\"attribute\"",
    "\"compose\"",
    "\"sugar\"",
    "\"rule\"",
    "\"priority\"",
    "\"default\"",
    "\"import\"",
    "\"tag\"",
    "\"space\"",
    "\"token\"",
    "\"fragment\"",
    "\"nested\"",
    "<T_META>",
    "<T_VAR>",
    "<T_CON>",
    "<T_SUFFIX>",
    "<T_NAME>",
    "<T_FRAGMENT_REF>",
    "<T_NATURAL>",
    "<T_INTEGER>",
    "<T_UNNATURAL>",
    "<T_STRING>",
    "<T_STRING1CHAR>",
    "<T_STRING2CHAR>",
    "<T_ESCAPEDCHAR>",
    "<T_HEX>",
    "<T_OTHERCHAR>",
    "<T_WORD>",
    "<T_CHAR_CLASS>",
    "\"^\"",
    "\"]\"",
    "\"-\"",
    "<T_CC_OTHER>",
  };

}
